export const CHANGE_INPUT_VALUE = 'CHANGE_INPUT_VALUE';
export const ADD_TODO_ITEM = 'ADD_TODO_ITEM';
export const DELETE_TODO_ITEM = 'DELETE_TODO_ITEM';
export const LOAD_List='LOAD_List';
export const LOAD_TASKLIST_SUCCESS='LOAD_TASKLIST_SUCCESS';
export const LOAD_List_SUCCESS='LOAD_List_SUCCESS';
export const LOAD_TASKLIST_ERROR='LOAD_TASKLIST_ERROR';
export const UPDATE_TODO_ITEM='UPDATE_TODO_ITEM';


